# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

Remotes: r-spatial/sf,
  tidyverse/knitr,
  tidyverse/dplyr,
  tidyverse/tidyr,
  tidyverse/tibble,
  tidyverse/stringr

after_success:
    - Rscript -e 'library(covr); codecov()'
