# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
    - sudo apt-get update
    - sudo apt-get install -y libudunits2-dev
    - sudo apt-get install -y libgdal-dev
    - sudo apt-get install -y libgeos-dev
    - sudo apt-get install -y libproj-dev

r_packages:
    - tidyverse

warnings_are_errors: true

after_success:
    - Rscript -e 'library(covr); codecov()'
