---
title: "Get going with nzcensr"
author: "Phil Donovan"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

The `nzcensr` package is mainly a data package to make it easy to perform normal and spatial analyses on the New Zealand census data.
It contains the following data sets:

```{r datasets, results='asis'}
library(nzcensr)
knitr::kable(nz_census_data())
```

At present, it only has two functions:

  1. `nz_census_data()` and
  2. `read_nz_census_data()`.
  
## An analysis

```{r analysis}
library(tidyverse)

# Read in data
dwelling_regions_long <- read_nz_census_data(dwelling_regions, 
                                          long = TRUE, 
                                          replace_confidential_values = NA_integer_, 
                                          include_gis = FALSE)

fuel_types_regions <- dwelling_regions_long %>% 
  filter(str_detect(variable, "Census_fuel_types_used_to_heat_dwellings_.*_for_occupied_private_d"))


```
